#!/bin/bash

r1c1=" "; r1c2=" "; r1c3=" ";
r2c1=" "; r2c2=" "; r2c3=" ";
r3c1=" "; r3c2=" "; r3c3=" ";

move_list="1,1 1,2 1,3 2,1 2,2 2,3 3,1 3,2 3,3"

show_board() {
   echo "$r1c1 | $r1c2 | $r1c3"
   echo "---------------------"
   echo "$r1c1 | $r1c2 | $r1c3"
   echo "---------------------"
   echo "$r1c1 | $r1c2 | $r1c3"
}

player_turn() {
   echo "Please choose a position:"
   select move in $move_list
   do
      if [[ -n $move ]]; then
         case $move in
            "1,1")
               r1c1="$1"
               ;;
            "1,2")
               r1c2="$1"
               ;;
            "1,3")
               r1c3="$1"
               ;;
            "2,1")
               r2c1="$1"
               ;;
            "2,2")
               r2c2="$1"
               ;;
            "2,3")
               r2c3="$1"
               ;;
            "3,1")
               r3c1="$1"
               ;;
            "3,2")
               r3c2="$1"
               ;;
            "3,3")
               r3c3="$1"
               ;;
          esac
      fi
   done
}
